title: St. Thomas Aquinas Catholic Church
author:
  name: Rev. Jordan C. Fetcko
  email: jfetcko@dcgary.org
description: |
  406 E Washington St.  
  Knox, IN 46534  
  (574) 772‑4134  
  parish@stthomasknox.org
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  hide_site_feed_link: true
  nav_pages:
    - about.md
