name: Deploy to Static.app
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Static.app
        uses: designmodo/static-app-deploy-action@v1.0.0
        with:
          api-key: ${{ secrets.STATIC_APP_API_KEY }}
          build-dir: './'
