name: Update Existing Site
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Static.app
        uses: designmodo/static-app-deploy-action@v1.0.0
        with:
          api-key: ${{ secrets.STATIC_APP_API_KEY }}
          pid: '5osqg4yudp'
          build-dir: 'build'
          build-command: 'npm install --package-lock-only && npm run build'
